APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:buL5jC9u/Uek/ZbnRctxBJ9FydztVbjiNw70ZsYh6BI=
APP_DEBUG=true
APP_URL=http://localhost:8000

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

#MYSQL_ADDON_HOST=bwssx0vjycpkxrrdavrc-mysql.services.clever-cloud.com
#MYSQL_ADDON_DB=bwssx0vjycpkxrrdavrc
#MYSQL_ADDON_USER=uba8j8ngsvxex9k5
#MYSQL_ADDON_PORT=3306
#MYSQL_ADDON_PASSWORD=wSLaRd03ZpmPU9pck5Jl
#MYSQL_ADDON_URI=mysql://uba8j8ngsvxex9k5:wSLaRd03ZpmPU9pck5Jl@bwssx0vjycpkxrrdavrc-mysql.services.clever-cloud.com:3306/bwssx0vjycpkxrrdavrc

DB_CONNECTION=mysql
DB_HOST=bwssx0vjycpkxrrdavrc-mysql.services.clever-cloud.com
DB_PORT=3306
DB_DATABASE=bwssx0vjycpkxrrdavrc
DB_USERNAME=uba8j8ngsvxex9k5
DB_PASSWORD=wSLaRd03ZpmPU9pck5Jl

#DB_CONNECTION=mysql
#DB_HOST=127.0.0.1
#DB_PORT=3306
#DB_DATABASE=smart_parking
#DB_USERNAME=root
#DB_PASSWORD=

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=sandbox.smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=your_mailtrap_username
MAIL_PASSWORD=your_mailtrap_password
MAIL_FROM_ADDRESS="no-reply@smartparking.com"
MAIL_FROM_NAME="Smart Parking"

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=your_gmail@gmail.com
MAIL_PASSWORD=your_app_password
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="your_gmail@gmail.com"
MAIL_FROM_NAME="Smart Parking"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"